"""initial schema

Revision ID: 7f22f9aee24b
Revises: 
Create Date: 2026-05-25 20:27:19.815438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f22f9aee24b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_ip', sa.String(length=45), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('feature_window_start', sa.DateTime(), nullable=False),
    sa.Column('feature_window_end', sa.DateTime(), nullable=False),
    sa.Column('raw_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('packet_length', sa.Integer(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('bandwidth_limit_kbps', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_rules')
    op.drop_table('network_events')
    op.drop_table('anomalies')
    op.drop_table('alerts')
    # ### end Alembic commands ###
